import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    'index': 'src/index.ts',
    'step-machine/index': 'src/step-machine/index.ts',
    'event-graph/index': 'src/event-graph/index.ts',
    'stores/index': 'src/stores/index.ts',
    'stores/memory': 'src/stores/memory.ts',
    'stores/localStorage': 'src/stores/localStorage.ts',
    'batch/index': 'src/batch/index.ts',
    'config/index': 'src/config/index.ts',
    'continuous-event-graph/index': 'src/continuous-event-graph/index.ts',
    'board-livegraph-runtime/index': 'src/board-livegraph-runtime/index.ts',
    'inference/index': 'src/inference/index.ts',
    'card-compute/index': 'src/card-compute/index.ts',
    'cli/node/board-live-cards-cli': 'src/cli/node/board-live-cards-cli.ts',
    'cli/node/fs-board-adapter': 'src/cli/node/fs-board-adapter.ts',
    'cli/node/card-store-cli': 'src/cli/node/card-store-cli.ts',
    'cli/node/source-cli-task-executor': 'src/cli/node/source-cli-task-executor.ts',
    'cli/browser-api/board-live-cards-browser-adapter': 'src/cli/browser-api/board-live-cards-browser-adapter.ts',
    'cli/browser-api/card-store-browser-api': 'src/cli/browser-api/card-store-browser-api.ts',
    'stores/file': 'src/stores/file.ts',
    'storage-refs': 'src/cli/node/public-storage-adapter.ts',
    'execution-refs': 'src/cli/common/execution-interface.ts',
  },
  format: ['esm', 'cjs'],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  minify: false,
  treeshake: true,
  target: 'es2022',
  outDir: 'dist',
});
