/**
 * public-storage-adapter.ts
 *
 * Standalone file — copy this to your task-executor project.
 * Zero dependencies on the rest of yaml-flow.
 *
 * Provides:
 *   - KindValueRef      wire format: b64:<base64url(json)>
 *   - parseRef()        parse a b64:<base64url(json)> string
 *   - serializeRef()    produce a b64:<base64url(json)> string
 *   - BlobStorage       read/write interface
 *   - blobStorageForRef resolve a ref to its BlobStorage backend
 *   - ExecutionRef      portable invocation descriptor (inlined, stays standalone)
 *   - TaskCallback      how to report task completion back to the board
 *   - reportComplete()  call from executor on success
 *   - reportFailed()    call from executor on failure
 *
 * Supported storage kinds:
 *   fs-path   — ref.value is an absolute file path; reads/writes via node:fs
 *
 * Supported callback transports (via ExecutionRef.howToRun):
 *   local-node     — invoke board CLI as a child Node process
 *   http:post      — HTTP POST to a board endpoint
 *
 * Usage:
 *   import { parseRef, blobStorageForRef, reportComplete, reportFailed } from './public-storage-adapter.js';
 *
 *   const { source_def, callback } = JSON.parse(blobStorageForRef(inRef).read(inRef.value));
 *   // ... do work, write to outRef ...
 *   reportComplete(callback, outRef);
 */
interface KindValueRef {
    readonly kind: string;
    readonly value: string;
}
/** Parse a wire-format ref string (b64:<base64url(json)>) into a KindValueRef. */
declare function parseRef(s: string): KindValueRef;
/** Serialize a KindValueRef to the wire format: b64:<base64url(json)> */
declare function serializeRef(ref: KindValueRef): string;
interface BlobStorage {
    /** Returns content string, or null if not found. */
    read(key: string): string | null;
    /** Write content at key. */
    write(key: string, content: string): void;
}
/**
 * Resolve a KindValueRef to its BlobStorage backend.
 * Throws a clear error for unrecognised kinds.
 */
declare function blobStorageForRef(ref: KindValueRef): BlobStorage;
/**
 * Portable invocation descriptor for the board CLI back-channel.
 * Inlined here so this file stays standalone (zero deps on yaml-flow internals).
 * Shape matches ExecutionRef in execution-interface.ts — keep in sync.
 *
 * Supported howToRun values for TaskCallback.via:
 *   local-node   — invoke board CLI as: node [tsx?] <whatToRun.value> <cmd> [...argv]
 *   http:post    — POST to <whatToRun.value> with a JSON body
 */
interface ExecutionRef {
    /** Optional human-readable label. Not used for dispatch. */
    meta?: string;
    /** Transport / runtime kind. */
    howToRun: 'local-node' | 'local-python' | 'local-process' | 'http:post' | 'http:get' | 'built-in';
    /** Address of the target in b64:<base64url(json)> wire form. */
    whatToRun: string;
    /** Opaque executor config stored with the ref. */
    extra?: Record<string, unknown>;
}
/**
 * Describes how the board wants to receive task completion callbacks.
 * Baked into the inRef payload as { source_def, callback }.
 * The executor treats `token` as opaque and passes it back unchanged.
 */
interface TaskCallback {
    /** Opaque routing token — generated by the board, passed back unchanged. */
    token: string;
    /** Delivery mechanism — an ExecutionRef pointing at the board CLI or endpoint. */
    via: ExecutionRef;
}
/**
 * Report successful task completion back to the board.
 * Call this from a task-executor after writing the result to outRef.
 */
declare function reportComplete(callback: TaskCallback, outRef: KindValueRef): void;
/**
 * Report task failure back to the board.
 * Call this from a task-executor instead of writing to outRef.
 */
declare function reportFailed(callback: TaskCallback, reason: string): void;

export { type BlobStorage, type ExecutionRef, type KindValueRef, type TaskCallback, blobStorageForRef, parseRef, reportComplete, reportFailed, serializeRef };
